//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinate
    {
        public Coordinate()
        {
            this.SolarObjects = new HashSet<SolarObject>();
            this.StarSystems = new HashSet<StarSystem>();
        }
    
        public int CoordinateId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Z { get; set; }
    
        public virtual ICollection<SolarObject> SolarObjects { get; set; }
        public virtual ICollection<StarSystem> StarSystems { get; set; }
    }
}
