//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faction
    {
        public Faction()
        {
            this.SolarObjects = new HashSet<SolarObject>();
        }
    
        public int FactionId { get; set; }
        public string FactionName { get; set; }
    
        public virtual ICollection<SolarObject> SolarObjects { get; set; }
    }
}
