//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreelancerServicesEntities : DbContext
    {
        public FreelancerServicesEntities()
            : base("name=FreelancerServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coordinate> Coordinates { get; set; }
        public virtual DbSet<Faction> Factions { get; set; }
        public virtual DbSet<SolarObject> SolarObjects { get; set; }
        public virtual DbSet<SolarObjectType> SolarObjectTypes { get; set; }
        public virtual DbSet<StarSystem> StarSystems { get; set; }
        public virtual DbSet<TradeLaneRing> TradeLaneRings { get; set; }
    }
}
