//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolarObject
    {
        public SolarObject()
        {
            this.StarSystems = new HashSet<StarSystem>();
            this.StarSystems1 = new HashSet<StarSystem>();
        }
    
        public int SolarObjectId { get; set; }
        public int CoordinateId { get; set; }
        public string SolarObjectName { get; set; }
        public int SolarObjectTypeId { get; set; }
    
        public virtual Coordinate Coordinate { get; set; }
        public virtual SolarObjectType SolarObjectType { get; set; }
        public virtual TradeLaneRing TradeLaneRing { get; set; }
        public virtual Faction Faction { get; set; }
        public virtual ICollection<StarSystem> StarSystems { get; set; }
        public virtual ICollection<StarSystem> StarSystems1 { get; set; }
    }
}
