//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarSystem
    {
        public StarSystem()
        {
            this.SolarObjects = new HashSet<SolarObject>();
            this.SolarObjects1 = new HashSet<SolarObject>();
        }
    
        public int StarSystemId { get; set; }
        public int CoordinateId { get; set; }
        public string StarSystemName { get; set; }
        public decimal ZoomScale { get; set; }
    
        public virtual Coordinate Coordinate { get; set; }
        public virtual ICollection<SolarObject> SolarObjects { get; set; }
        public virtual ICollection<SolarObject> SolarObjects1 { get; set; }
    }
}
