//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataScanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeLaneRing
    {
        public TradeLaneRing()
        {
            this.TradeLaneRing1 = new HashSet<TradeLaneRing>();
        }
    
        public int TradeLaneRingId { get; set; }
        public Nullable<int> ConnectsToTradeLaneRingId { get; set; }
        public Nullable<bool> IsEndPoint { get; set; }
    
        public virtual SolarObject SolarObject { get; set; }
        public virtual ICollection<TradeLaneRing> TradeLaneRing1 { get; set; }
        public virtual TradeLaneRing TradeLaneRing2 { get; set; }
    }
}
